### ISSUE TITLE
Error with Hyva themes

### ISSUE THREAD

**Issue by mpchadwick** [outeredge/magento-structured-data-module#69]
This module causes an error with the default Hyva theme.

```
Error: Call to a member function getJsonConfigurationHtmlEscaped() on null in /var/www/html/vendor/magento/module-catalog/view/frontend/templates/product/breadcrumbs.phtml:12
```

Here is what I believe is happening:

This layout directive references the following template path: `Magento_Catalog::product/breadcrumbs.phtml`

```
vendor/outeredge/magento-structured-data-module/view/frontend/layout/catalog_product_view.xml:                <argument name="template" xsi:type="string">Magento_Catalog::product/breadcrumbs.phtml</argument>
```

Hyva puts the template at `Magento_Catalog::product/view/breadcrumbs.phtml`, however, so Magento loads the template from `vendor/magento/module-catalog` instead of `vendor/hyva-themes/magento2-default-theme`.

The template at `vendor/magento/module-catalog` references a `viewModel` which isn't defined in

`vendor/hyva-themes/magento2-default-theme/Magento_Catalog/layout/catalog_product_view.xml`

As such it triggers the error

**Comment by ollyijb** [comment]
Hi mpchadwick, we will raise an internal task for this and get back to you. Thanks!

**Comment by ollyijb** [comment]
Hi mpchadwick,

We were unable to reproduce this issue using:

Magento ver. 2.4.6-p4
"hyva-themes/magento2-default-theme": "1.3.2" 
"outeredge/magento-structured-data-module": "4.0.10"

Can you please let me know which versions you are using?

Thanks!

**Comment by rhoerr** [comment]
I'm getting this same error on current versions.

Magento ver. 2.4.7-p3
"hyva-themes/magento2-default-theme": "1.3.9"
"outeredge/magento-structured-data-module": "5.0.9"

**Comment by rhoerr** [comment]
For Hyva compatibility, I had to override `vendor/outeredge/magento-structured-data-module/view/frontend/layout/catalog_product_view.xml` to remove
```
        <referenceBlock name="breadcrumbs" template="Magento_Catalog::product/breadcrumbs.phtml"/>
```

and override `vendor/outeredge/magento-structured-data-module/view/frontend/templates/html/breadcrumbs.phtml` to replace the actual breadcrumbs HTML with Hyva's version from `vendor/hyva-themes/magento2-default-theme/Magento_Theme/templates/html/breadcrumbs.phtml`. Otherwise, the breadcrumbs are not properly styled and miss aria tags.

You should add Hyva-specific layout and template files to this package if you're going to call it Hyva compatible. 🙂

**Comment by davidwindell** [comment]
@rhoerr you're very welcome to raise a pull request, this is an open source project :)

**Comment by rhoerr** [comment]
Of course. At any rate, could you reopen this issue for tracking? Thanks

**Comment by davidwindell** [comment]
@rhoerr see if #86 helps (removes our Breadcrumbs logic on Hyva). If not feel free to push up changes.
